-- Create api_keys table for hardware authentication
CREATE TABLE IF NOT EXISTS public.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id VARCHAR REFERENCES public.schools(id) NOT NULL,
    key_hash TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    last_used_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true
);

-- Enable RLS
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- Policy: Only super_admin or school admin can manage keys
CREATE POLICY "Manage keys" ON public.api_keys
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.user_profiles
            WHERE user_profiles.id = auth.uid()
            AND (user_profiles.role = 'super_admin' OR (user_profiles.role = 'admin' AND user_profiles.school_id = api_keys.school_id))
        )
    );