-- Create school_events table
CREATE TABLE IF NOT EXISTS public.school_events (
    id bigint generated by default as identity primary key,
    school_id varchar not null references public.schools(id) on delete cascade,
    title varchar not null,
    content text not null,
    image_url text null,
    event_date timestamptz null,
    published_at timestamptz not null default now(),
    created_by uuid null references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Apply explicit grants to public.school_events
GRANT ALL ON public.school_events TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.school_events TO authenticated;

-- Enable Row Level Security
ALTER TABLE public.school_events ENABLE ROW LEVEL SECURITY;

-- Policy for school admin/teacher (ALL access)
CREATE POLICY "admin_teacher_all_events" 
ON public.school_events
AS PERMISSIVE FOR ALL
TO authenticated
USING (
    (auth.jwt()->>'role' IN ('admin', 'teacher')) AND 
    (auth.jwt()->>'school_id' = school_id)
)
WITH CHECK (
    (auth.jwt()->>'role' IN ('admin', 'teacher')) AND 
    (auth.jwt()->>'school_id' = school_id)
);

-- Policy for parent (SELECT only)
CREATE POLICY "parent_read_events"
ON public.school_events
AS PERMISSIVE FOR SELECT
TO authenticated
USING (
    (auth.jwt()->>'role' = 'parent') AND 
    (auth.jwt()->>'school_id' = school_id)
);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_school_events_school_published 
ON public.school_events(school_id, published_at DESC);